# Generated by Django 4.2.5 on 2023-11-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_id', models.IntegerField()),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.IntegerField()),
                ('reserver_name', models.TextField()),
                ('reserver_tel', models.TextField()),
                ('reserver_num', models.IntegerField()),
                ('reserver_allergy', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('tel', models.TextField()),
                ('post_code', models.TextField()),
                ('address', models.TextField()),
                ('seat_num', models.IntegerField()),
            ],
        ),
    ]
